net-misc/onedrive: add 2.5.3
gentoo/dlang pull request #133
Opened 2024-12-08 12:32 UTC by douglarek

I have been using OneDrive version 2.5 for a long time, and now version 2.5.3 is very stable. I recommend checking in.

2024-12-08 15:51 UTC, the-horo requested changes
Thank you for contributing.

I only have one minor nit with the ebuild but onedrive-2.5 seems to be working fine otherwise. @MrDuartePT is the maintainer, however, so let's see what he has to say.

2024-12-08 15:52 UTC, the-horo commented on net-misc/onedrive/onedrive-2.5.3.ebuild
> +}
Upstream mentions that the 2.5 releases are not backward-compatible with 2.4 and some care needs to be taken like making sure you update all your devices to 2.5. I think the user should be warned about this.

```suggestion

	local old_ver minor_part="$(ver_cut 1-2)"
	for old_ver in "${REPLACING_VERSIONS[@]}"; do
		if ver_test "${old_ver}" -lt "${minor_part}"; then
			ewarn "You are performing an upgrade that is not backwards-compatible"
			ewarn "and you need to upgrade to ${PN}-${minor_part} on all your devices."
			ewarn "Please read: https://github.com/abraunegg/onedrive/releases/tag/v${PV}"
			break
		fi
	done
}
```

2024-12-09 13:38 UTC, the-horo commented
Can you squash the second commit so we would be left with a single one? It:
1. keeps the history cleaner
2. preserves the `Signed-off-by: `. As per the [Gentoo copyright policy](https://devmanual.gentoo.org/general-concepts/copyright-policy/index.html#certificate-of-origin), each commit must be `--signoff`'ed in order to be merged.

2024-12-09 14:16 UTC, the-horo approved these changes

2024-12-16 21:34 UTC, MrDuartePT commented
> Can you squash the second commit so we would be left with a single one? It:
> 
> 1. keeps the history cleaner
> 
> 2. preserves the `Signed-off-by: `. As per the [Gentoo copyright policy](https://devmanual.gentoo.org/general-concepts/copyright-policy/index.html#certificate-of-origin), each commit must be `--signoff`'ed in order to be merged.

Everthing look ok I didn't update the ebuild when that version release because of the warning that is not backwards compatible with 2.4.x

https://github.com/abraunegg/onedrive/releases/tag/v2.5.3

Thanks for the PR, but I think it better to mask this version until some user test it.

2024-12-16 21:38 UTC, MrDuartePT commented
This program is mission critical for me since I use it to sync my uni OneDrive that why I didn't want to risk breaking something.

2024-12-17 07:35 UTC, the-horo commented
I think it's fine to merge this PR with `KEYWORDS=''` and then add `~amd64` after some time, corresponding to upstream releases becoming more stable to avoid big bugs like in https://github.com/abraunegg/onedrive/releases/tag/v2.5.1. This should help with users testing the package while avoiding issues for people who depend on the package working. @MrDuartePT does this sound reasonable?

2024-12-18 07:43 UTC, MrDuartePT commented
> @MrDuartePT does this sound reasonable?

Yes it sound reasonable to me.

2024-12-18 11:20 UTC, closed without merging